# NoiseMap AI Configuration
model:
  catboost:
    iterations: 1000
    learning_rate: 0.1
    depth: 6
    l2_leaf_reg: 3
    random_seed: 42

  firefly:
    population_size: 30
    max_generations: 50
    alpha: 0.2
    beta: 1.0
    gamma: 0.01

  fruitfly:
    population_size: 20
    max_iterations: 100
    step_size: 0.1

data:
  sample_rate: 22050
  duration: 5 # seconds
  n_mfcc: 13
  n_fft: 2048
  hop_length: 512

features:
  audio_features:
    - mfcc
    - spectral_centroid
    - spectral_rolloff
    - zero_crossing_rate
    - chroma
    - mel_spectrogram

  contextual_features:
    - hour_of_day
    - day_of_week
    - weather_condition
    - location_type
    - traffic_density

health_impact:
  sleep_disruption_threshold: 45 # dB
  stress_threshold: 55 # dB
  hearing_damage_threshold: 85 # dB
