# Generated by Django 4.2.9 on 2025-07-24 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("noise_detection", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="noisearea",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
